version: '3.1'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    # Wait for mongoose to be ready
    command: ["./resources/wait_for.sh", "db:27017", "--", "npm", "run", "serve"]
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
  
  # client:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - server
  #   restart: unless-stopped
  #   volumes:
  #     - ./frontend:/app
  #     - frontend_node_modules:/app/node_modules
  #   environment: 
  #     - CHOKIDAR_USEPOLLING=true
  #   command: ["yarn", "serve"]
  
  # To access sql console from the db container:
  # psql --host=db --username=spsproject --dbname=sps_project_dev
  db:
    image: mongo
    restart: always
    env_file: ./backend/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

# To remove volumes:
# docker volume rm $(docker volume ls -q)
volumes:
  mongodb:
  backend_node_modules:
  #frontend_node_modules: